services:
  db:
    image: mariadb:10.11
    container_name: seafile-db
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_LOG_CONSOLE=true
    volumes:
    - ./data/db:/var/lib/mysql
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: seafile_redis
    restart: always
    volumes:
    - redis_data:/data
    ports:
    - 6379:6379
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    depends_on:
    - db
    - redis
    environment:
    - DB_HOST=db
    - DB_ROOT_PASSWD=${MYSQL_ROOT_PASSWORD}
    - TIME_ZONE=${SEAFILE_TIME_ZONE}
    - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
    - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
    - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME}
    - SEAFILE_SERVER_PROTOCOL=http
    volumes:
    - ./seafile:/shared
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: seafile-nginx
    depends_on:
    - seafile
    ports:
    - ${HTTPS_PORT}:8443
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
volumes:
  redis_data: {}
